---
-
        name: install web server
        hosts: webservers
        become: yes
        tasks:
                -
                        name: install package
                        yum:
                                name: httpd
                                state: present
                -
                        name: start the service
                        service:
                                name: httpd
                                state: started

